package cn.wong.pojo;

import java.util.Date;

public class Dindan {

    private Integer id;

    private String dingdanbianhao;

    private String yonghuming;

    private String shangpinxinxi;

    private String wuliudanhao;

    private Integer dingdanzonge;

    private Date dingdanshijian;

    private Integer dingdanzhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dindan.ShouHuoDiZhi
     *
     * @mbg.generated
     */
    private String shouhuodizhi;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDingdanbianhao() {
        return dingdanbianhao;
    }

    public void setDingdanbianhao(String dingdanbianhao) {
        this.dingdanbianhao = dingdanbianhao == null ? null : dingdanbianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.YongHuMing
     *
     * @return the value of dindan.YongHuMing
     *
     * @mbg.generated
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.YongHuMing
     *
     * @param yonghuming the value for dindan.YongHuMing
     *
     * @mbg.generated
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.ShangPinXinXi
     *
     * @return the value of dindan.ShangPinXinXi
     *
     * @mbg.generated
     */
    public String getShangpinxinxi() {
        return shangpinxinxi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.ShangPinXinXi
     *
     * @param shangpinxinxi the value for dindan.ShangPinXinXi
     *
     * @mbg.generated
     */
    public void setShangpinxinxi(String shangpinxinxi) {
        this.shangpinxinxi = shangpinxinxi == null ? null : shangpinxinxi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.WuLiuDanHao
     *
     * @return the value of dindan.WuLiuDanHao
     *
     * @mbg.generated
     */
    public String getWuliudanhao() {
        return wuliudanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.WuLiuDanHao
     *
     * @param wuliudanhao the value for dindan.WuLiuDanHao
     *
     * @mbg.generated
     */
    public void setWuliudanhao(String wuliudanhao) {
        this.wuliudanhao = wuliudanhao == null ? null : wuliudanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.DingDanZongE
     *
     * @return the value of dindan.DingDanZongE
     *
     * @mbg.generated
     */
    public Integer getDingdanzonge() {
        return dingdanzonge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.DingDanZongE
     *
     * @param dingdanzonge the value for dindan.DingDanZongE
     *
     * @mbg.generated
     */
    public void setDingdanzonge(Integer dingdanzonge) {
        this.dingdanzonge = dingdanzonge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.DingDanShiJian
     *
     * @return the value of dindan.DingDanShiJian
     *
     * @mbg.generated
     */
    public Date getDingdanshijian() {
        return dingdanshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.DingDanShiJian
     *
     * @param dingdanshijian the value for dindan.DingDanShiJian
     *
     * @mbg.generated
     */
    public void setDingdanshijian(Date dingdanshijian) {
        this.dingdanshijian = dingdanshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.DingDanZhuangTai
     *
     * @return the value of dindan.DingDanZhuangTai
     *
     * @mbg.generated
     */
    public Integer getDingdanzhuangtai() {
        return dingdanzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.DingDanZhuangTai
     *
     * @param dingdanzhuangtai the value for dindan.DingDanZhuangTai
     *
     * @mbg.generated
     */
    public void setDingdanzhuangtai(Integer dingdanzhuangtai) {
        this.dingdanzhuangtai = dingdanzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dindan.ShouHuoDiZhi
     *
     * @return the value of dindan.ShouHuoDiZhi
     *
     * @mbg.generated
     */
    public String getShouhuodizhi() {
        return shouhuodizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dindan.ShouHuoDiZhi
     *
     * @param shouhuodizhi the value for dindan.ShouHuoDiZhi
     *
     * @mbg.generated
     */
    public void setShouhuodizhi(String shouhuodizhi) {
        this.shouhuodizhi = shouhuodizhi == null ? null : shouhuodizhi.trim();
    }
}