package cn.wong.test;

import cn.wong.test.Kefudenglu;

public interface KefudengluMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    int insert(Kefudenglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    int insertSelective(Kefudenglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    Kefudenglu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Kefudenglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kefudenglu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Kefudenglu record);
}