package cn.wong.test;

import java.util.Date;

public class Kefudenglu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.XingMing
     *
     * @mbg.generated
     */
    private String xingming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.ShouJiHaoMa
     *
     * @mbg.generated
     */
    private String shoujihaoma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.MiMa
     *
     * @mbg.generated
     */
    private String mima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.ZhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.ShenFenZheng
     *
     * @mbg.generated
     */
    private String shenfenzheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.ZuiHouDengLu
     *
     * @mbg.generated
     */
    private Date zuihoudenglu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.ZuiHouQianDao
     *
     * @mbg.generated
     */
    private Date zuihouqiandao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.CuoWuCiShu
     *
     * @mbg.generated
     */
    private Integer cuowucishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.YouXiang
     *
     * @mbg.generated
     */
    private String youxiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.XingBie
     *
     * @mbg.generated
     */
    private String xingbie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kefudenglu.qiandaocishu
     *
     * @mbg.generated
     */
    private Integer qiandaocishu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.id
     *
     * @return the value of kefudenglu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.id
     *
     * @param id the value for kefudenglu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.XingMing
     *
     * @return the value of kefudenglu.XingMing
     *
     * @mbg.generated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.XingMing
     *
     * @param xingming the value for kefudenglu.XingMing
     *
     * @mbg.generated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.ShouJiHaoMa
     *
     * @return the value of kefudenglu.ShouJiHaoMa
     *
     * @mbg.generated
     */
    public String getShoujihaoma() {
        return shoujihaoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.ShouJiHaoMa
     *
     * @param shoujihaoma the value for kefudenglu.ShouJiHaoMa
     *
     * @mbg.generated
     */
    public void setShoujihaoma(String shoujihaoma) {
        this.shoujihaoma = shoujihaoma == null ? null : shoujihaoma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.MiMa
     *
     * @return the value of kefudenglu.MiMa
     *
     * @mbg.generated
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.MiMa
     *
     * @param mima the value for kefudenglu.MiMa
     *
     * @mbg.generated
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.ZhuangTai
     *
     * @return the value of kefudenglu.ZhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.ZhuangTai
     *
     * @param zhuangtai the value for kefudenglu.ZhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.ShenFenZheng
     *
     * @return the value of kefudenglu.ShenFenZheng
     *
     * @mbg.generated
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.ShenFenZheng
     *
     * @param shenfenzheng the value for kefudenglu.ShenFenZheng
     *
     * @mbg.generated
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.ZuiHouDengLu
     *
     * @return the value of kefudenglu.ZuiHouDengLu
     *
     * @mbg.generated
     */
    public Date getZuihoudenglu() {
        return zuihoudenglu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.ZuiHouDengLu
     *
     * @param zuihoudenglu the value for kefudenglu.ZuiHouDengLu
     *
     * @mbg.generated
     */
    public void setZuihoudenglu(Date zuihoudenglu) {
        this.zuihoudenglu = zuihoudenglu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.ZuiHouQianDao
     *
     * @return the value of kefudenglu.ZuiHouQianDao
     *
     * @mbg.generated
     */
    public Date getZuihouqiandao() {
        return zuihouqiandao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.ZuiHouQianDao
     *
     * @param zuihouqiandao the value for kefudenglu.ZuiHouQianDao
     *
     * @mbg.generated
     */
    public void setZuihouqiandao(Date zuihouqiandao) {
        this.zuihouqiandao = zuihouqiandao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.CuoWuCiShu
     *
     * @return the value of kefudenglu.CuoWuCiShu
     *
     * @mbg.generated
     */
    public Integer getCuowucishu() {
        return cuowucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.CuoWuCiShu
     *
     * @param cuowucishu the value for kefudenglu.CuoWuCiShu
     *
     * @mbg.generated
     */
    public void setCuowucishu(Integer cuowucishu) {
        this.cuowucishu = cuowucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.YouXiang
     *
     * @return the value of kefudenglu.YouXiang
     *
     * @mbg.generated
     */
    public String getYouxiang() {
        return youxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.YouXiang
     *
     * @param youxiang the value for kefudenglu.YouXiang
     *
     * @mbg.generated
     */
    public void setYouxiang(String youxiang) {
        this.youxiang = youxiang == null ? null : youxiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.XingBie
     *
     * @return the value of kefudenglu.XingBie
     *
     * @mbg.generated
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.XingBie
     *
     * @param xingbie the value for kefudenglu.XingBie
     *
     * @mbg.generated
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kefudenglu.qiandaocishu
     *
     * @return the value of kefudenglu.qiandaocishu
     *
     * @mbg.generated
     */
    public Integer getQiandaocishu() {
        return qiandaocishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kefudenglu.qiandaocishu
     *
     * @param qiandaocishu the value for kefudenglu.qiandaocishu
     *
     * @mbg.generated
     */
    public void setQiandaocishu(Integer qiandaocishu) {
        this.qiandaocishu = qiandaocishu;
    }
}